name: roulette_game
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  assets_audio_player: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/roulette_bg.jpeg
  - assets/sample.png
  - assets/roulette_App_3000.jpg
  - assets/runderrandaussen.png
  - assets/rouletterad.png
  - assets/roulette_sound1.mp3
  - assets/buttonSound.mp3
  - assets/cashSound.mp3